CREATE DATABASE PARTNER_GROUP;

USE PARTNER_GROUP;

CREATE TABLE MARCA(
NOME VARCHAR (255) UNIQUE NOT NULL,
MARCAID INT IDENTITY PRIMARY KEY
);

CREATE TABLE PATRIMONIO(
NOME VARCHAR (255) NOT NULL,
MARCAID INT FOREIGN KEY REFERENCES MARCA(MARCAID) NOT NULL,
DESCRICAO TEXT,
NUMERO_TOMBO INT IDENTITY PRIMARY KEY
);

//sa   S#nai@132